version: 2.1

jobs:
  build:
    docker:
      - image: maven:3-amazoncorretto-21
    steps:
      - checkout
      - run:
          name: Build the application
          command: mvn clean package
      - persist_to_workspace:
          root: ./
          paths:
            - target/  # Persist the target directory to the workspace

  build-and-push-docker-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./  # Attach the workspace to restore the target directory
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_HUB_USERNAME/mavenwebapp:v6 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_HUB_USERNAME/mavenwebapp:v6


workflows:
  version: 2
  build-and-push-and-deploy:
    jobs:
      - build
      - build-and-push-docker-image:
          requires:
            - build