version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build the application
          command: mvn clean package

  build-docker-image:
    docker:
      - image: circleci/docker:19.03.12-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t sivavel/mavenwebapp:latest .
            echo $Docker_PASSWORD | docker login -u $Docker_UserName --password-stdin
            docker push sivavel/mavenwebapp:latest

  deploy-to-eks:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: Configure AWS CLI
          command: |
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - run:
          name: Update kubeconfig
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy to EKS
          command: |
            kubectl apply -f mavenweb.yaml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-docker-image:
          requires:
            - build
      - deploy-to-eks:
          requires:
            - build-docker-image