version: 2.1

jobs:
  build-and-push-docker-image:
    docker:
      - image: tomcat:8.0.20-jre8
    steps:
      - checkout
      - run:
          name: Build the application
          command: mvn clean package
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t sivavel/mavenwebapp:v5 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push sivavel/mavenwebapp:v5

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push-docker-image


  
       