version: 2.1

jobs:
  build:
    docker:
      - image: maven:3-amazoncorretto-21
    steps:
      - checkout
      - run:
          name: Build the application
          command: mvn clean package
      - persist_to_workspace:
          root: ./
          paths:
            - target/  # Persist the target directory to the workspace

  build-and-push-docker-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./  # Attach the workspace to restore the target directory
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_HUB_USERNAME/mavenwebapp:v5 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_HUB_USERNAME/mavenwebapp:v5

  deploy-to-eks:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Install tar and gzip utilities
          command: |
            yum install -y tar gzip  # Install tar and gzip using yum in the amazon/aws-cli image
      - attach_workspace:
          at: ./  # Attach the workspace to access the repository files
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set default.region "$AWS_DEFAULT_REGION"
      - run:
          name: Update kubeconfig for EKS cluster
          command: |
            aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy to EKS
          command: |
            kubectl apply -f kubernetes/mavenwebappdeployment.yaml  # Correct path to mavenwebappdeployment.yaml

workflows:
  version: 2
  build-and-push-and-deploy:
    jobs:
      - build
      - build-and-push-docker-image:
          requires:
            - build
      - deploy-to-eks:
          requires:
            - build-and-push-docker-image